# Generated by Django 4.1.5 on 2023-01-18 01:48

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('qualified', models.BooleanField(default=True)),
                ('origin_image', models.ImageField(null=True, upload_to=core.models.origin_image_file_path)),
                ('origin_pos', models.CharField(max_length=255, null=True)),
                ('update_image', models.ImageField(null=True, upload_to=core.models.update_image_file_path)),
                ('update_pos', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
